title: My Reference Portal
description: Curated references to blogs and LinkedIn articles

# GitHub Pages Settings
baseurl: "/username" # The subpath of your site (REQUIRED if hosted at username.github.io/username)
url: "https://username.github.io" # The base hostname & protocol

# Theme
theme: minima

# SASS compression
sass:
  style: compressed

# Defaults for layout and CSS
defaults:
  - scope:
      path: ""
    values:
      layout: default
      css: /assets/css/style.css

# Allow future dated posts to show
future: true
